---
- hosts: localhost
  connection: local
  become: true
  become_user: root

  tasks:
  - name: start docker
    service: name=docker state=restarted
  - name: loginto docker
    command: docker login --username rsadhukhan --password XXY#760Qbe
  - name: build dockerfile
    command: docker build -t rsadhukhan/train-schedule .
  - name: push dockerfile to dockerhub
    command: docker push rsadhukhan/train-schedule
